version: '2.1'

networks:
  servers:

services:

  server1:
    build: .
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build: .
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    build: .
    networks:
      - servers
    ports:
      - "8082:8080"
  
  balancer:
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"
    depends_on:
      - server1
      - server2
      - server3
